from marshmallow import Schema, fields, validate


SITE_STATUSES = ("operational", "maintenance", "offline")


class SiteCreateSchema(Schema):
    site_code = fields.String(
        required=True,
        validate=validate.Length(min=1, max=50),
        metadata={"description": "Operational identifier for the site."},
    )
    name = fields.String(
        required=True,
        validate=validate.Length(min=1, max=100),
        metadata={"description": "Telecommunications site name."},
    )
    latitude = fields.Float(
        required=True,
        validate=validate.Range(min=-90, max=90),
        metadata={"description": "Site latitude in decimal degrees."},
    )
    longitude = fields.Float(
        required=True,
        validate=validate.Range(min=-180, max=180),
        metadata={"description": "Site longitude in decimal degrees."},
    )
    status = fields.String(
        load_default="operational",
        validate=validate.OneOf(SITE_STATUSES),
        metadata={"description": "Current operating state of the site."},
    )


class SiteUpdateSchema(Schema):
    name = fields.String(
        validate=validate.Length(min=1, max=100),
    )
    latitude = fields.Float(
        validate=validate.Range(min=-90, max=90),
    )
    longitude = fields.Float(
        validate=validate.Range(min=-180, max=180),
    )
    status = fields.String(
        validate=validate.OneOf(SITE_STATUSES),
    )


class SiteSchema(SiteCreateSchema):
    id = fields.Integer(
        dump_only=True,
        metadata={"description": "Unique identifier generated by the API."},
    )
    created_at = fields.DateTime(
        dump_only=True,
        metadata={"description": "Date and time when the site was created."},
    )
    updated_at = fields.DateTime(
        dump_only=True,
        metadata={"description": "Date and time when the site was last updated."},
    )