"""Create sites table

Revision ID: be46c1c6dc81
Revises:
Create Date: 2026-09-25 10:51:14.855701

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'be46c1c6dc81'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='operational', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('operational', 'maintenance', 'offline')", name='ck_sites_status'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_sites_latitude_range'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_sites_longitude_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_site_code'), ['site_code'], unique=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_site_code'))

    op.drop_table('sites')
    # ### end Alembic commands ###